# Generated by Django 4.2.7 on 2025-08-15 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network_name', models.CharField(choices=[('ganache', 'Ganache (Local)'), ('ethereum', 'Ethereum Mainnet'), ('sepolia', 'Sepolia Testnet'), ('polygon', 'Polygon')], max_length=50, unique=True)),
                ('rpc_url', models.URLField()),
                ('chain_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blockchain Network',
                'verbose_name_plural': 'Blockchain Networks',
                'ordering': ['network_name'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('transaction_type', models.CharField(choices=[('vote', 'Vote Transaction'), ('deploy', 'Contract Deployment'), ('config', 'Configuration Update')], max_length=20)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('gas_price', models.BigIntegerField(blank=True, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=66)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_hash', models.CharField(max_length=64)),
                ('party_id', models.UUIDField()),
                ('vote_timestamp', models.BigIntegerField()),
                ('merkle_proof', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blockchain_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vote_record', to='blockchain.blockchaintransaction')),
            ],
            options={
                'verbose_name': 'Vote Record',
                'verbose_name_plural': 'Vote Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_name', models.CharField(max_length=100)),
                ('contract_address', models.CharField(max_length=42)),
                ('abi', models.JSONField()),
                ('bytecode', models.TextField(blank=True)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('deployment_tx_hash', models.CharField(blank=True, max_length=66)),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='blockchain.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Smart Contract',
                'verbose_name_plural': 'Smart Contracts',
                'ordering': ['-deployed_at'],
                'unique_together': {('contract_address', 'network')},
            },
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.smartcontract'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.blockchainnetwork'),
        ),
        migrations.CreateModel(
            name='BlockchainAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('vote_cast', 'Vote Cast'), ('vote_verified', 'Vote Verified'), ('contract_deployed', 'Contract Deployed'), ('network_changed', 'Network Changed'), ('audit_performed', 'Audit Performed')], max_length=30)),
                ('description', models.TextField()),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='blockchain.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Blockchain Audit Log',
                'verbose_name_plural': 'Blockchain Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
