# Generated by Django 4.2.7 on 2025-08-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='phone_number',
            field=models.CharField(default='', help_text='Phone number with country code', max_length=15),
        ),
        migrations.AddField(
            model_name='voter',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='voter_profiles/'),
        ),
        migrations.AddField(
            model_name='voter',
            name='region',
            field=models.CharField(default='', help_text='State or region', max_length=200),
        ),
        migrations.AddField(
            model_name='voter',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
