# Generated by Django 4.2.7 on 2025-08-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voter_email_verified_voter_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalparty',
            name='party_symbol',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='party_symbol_content_type',
            field=models.CharField(blank=True, help_text='MIME type of the party symbol', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='party_symbol_data',
            field=models.BinaryField(blank=True, help_text='Binary data of the party symbol image', null=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='party_symbol_name',
            field=models.CharField(blank=True, help_text='Original filename of the party symbol', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='party_symbol_size',
            field=models.PositiveIntegerField(blank=True, help_text='Size of the party symbol in bytes', null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='profile_picture_content_type',
            field=models.CharField(blank=True, help_text='MIME type of the profile picture', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='profile_picture_data',
            field=models.BinaryField(blank=True, help_text='Binary data of the profile picture', null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='profile_picture_name',
            field=models.CharField(blank=True, help_text='Original filename of the profile picture', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='profile_picture_size',
            field=models.PositiveIntegerField(blank=True, help_text='Size of the profile picture in bytes', null=True),
        ),
    ]
