# Generated by Django 4.2.7 on 2025-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_politicalparty_party_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='party_id',
            field=models.CharField(blank=True, help_text='Unique party identification code (e.g., BJP, INC, AAP)', max_length=20, null=True, unique=True),
        ),
    ]
