# Generated by Django 4.2.7 on 2025-08-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_add_party_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='party_id',
            field=models.CharField(help_text='Unique party identification code (e.g., BJP, INC, AAP)', max_length=20, unique=True),
        ),
    ]
